// <auto-generated />
namespace IdeaCollectorSH.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class z20032020 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(z20032020));
        
        string IMigrationMetadata.Id
        {
            get { return "202003201156102_z20032020"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
