// <auto-generated />
namespace IdeaCollectorSH.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class z2027 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(z2027));
        
        string IMigrationMetadata.Id
        {
            get { return "202003192027361_z2027"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
